### ISSUE TITLE
Don't use trans()

### ISSUE THREAD

**Issue by alxy** [gabsource/oc-scaffold-translation-plugin#1]
Hi,

actually this is a useful plugin, but all the calls to `trans()` are unneccessary. October will automatically look up these in the language files - there is no need for the trans in Components, Plugin-files, etc

Example: https://github.com/rainlab/blog-plugin/blob/master/components/Categories.php#L30-L31

**Comment by gabsource** [comment]
Thanks for feedback. Only found unnecessary `trans` in component stub. If you found others, let me know.

**Comment by alxy** [comment]
Hi, you are right :)
But I think in PHP files you should use the `Lang::get()` method, whereas in view files the `trans()` helper should be used. At least in the october core it is handled like that.

**Comment by gabsource** [comment]
Your are right, it's reverted.
