### ISSUE TITLE
Controller onDelete behavior

### ISSUE THREAD

**Issue by viamage** [gabsource/oc-scaffold-translation-plugin#9]
Hello,

Thank you for your awesome plugin. I've got a question though, can bring PR if you are willing.

Basically, you scaffold controller with delete button and onDelete method like this:

```php
public function index_onDelete()
{
    if (($checkedIds = post('checked')) && is_array($checkedIds) && count($checkedIds)) {
        foreach ($checkedIds as ${{lower_singular_model}}Id) {
            if (!${{lower_singular_model}} = {{model}}::find(${{lower_singular_model}}Id)) continue;
                ${{lower_singular_model}}->delete();
        }
    }
    (...)
}
```

and it does what should rarely be done: makes singular queries in loop, also loads whole model with find and does some non required checks. That makes it super slow, for 120 records at once I've got like 5 seconds deletion time.

My suggestion would be to use:

```php
if (($checkedIds = post('checked')) && is_array($checkedIds) && count($checkedIds)) {
  {{model}}::whereIn('id', $checkedIds)->delete();  
}
```

so results would be like

```php
if (($checkedIds = post('checked')) && is_array($checkedIds) && count($checkedIds)) {
  Model::whereIn('id', $checkedIds)->delete();
}
```

Rationale:
- You do not really need to confirm that model exists and load it with find when you just want to delete it.
- You do not need to spam database with queries when you want one operation to go and have array of ids.
- There is HUGE speed difference:

Loop method for 120 records: 5116 ms (red on screenshot)
Wherein method for 120 records: 121ms (green on screenshot)

![db](https://i.viamage.com/jz/screen-2018-04-29-11-59-20.png)

Let me know if you would be willing to accept PR for this?

**Comment by gabsource** [comment]
Hi,

If I remember, the loop is to call events on models (`beforeDelete` / `afterDelete`). Those were not called with the bulk `Model::delete`.

I dont see any other reason.
